name: Run app

on:
  schedule:
  - cron: '25 15 * * 1-5'
  - cron: '45 15 * * 5'

jobs:
  podium-jour:

    runs-on: ubuntu-latest
    if: github.event.schedule == '25 15 * * 1-5'

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run podium jour with Maven
      run: mvn spring-boot:run -Dspring-boot.run.arguments="jour"
      env:
        SLACK_TOKEN: ${{ secrets.SlackToken }}
        SLACK_CHANNEL: ${{ secrets.SlackChannel }}

  podium-semaine:

    runs-on: ubuntu-latest
    if: github.event.schedule == '45 15 * * 5'

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run podium semaine with Maven
      run: mvn spring-boot:run -Dspring-boot.run.arguments="semaine"
      env:
        SLACK_TOKEN: ${{ secrets.SlackToken }}
        SLACK_CHANNEL: ${{ secrets.SlackChannel }}