name: Run app

on:
  schedule:
  - cron: '30 15 * * 1-5'

jobs:
  podium-jour:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run podium jour with Maven
      run: mvn spring-boot:run -Dspring-boot.run.arguments="jour"
      env:
        SLACK_TOKEN: ${{ secrets.SlackToken }}
        SLACK_CHANNEL: ${{ secrets.SlackChannel }}
